/* ===== EDITION DATA — each edition replaces this block ===== */
const EDITION = {
  name: "Evening Edition",
  date: "Tuesday, 6 October 2026",
  pressTime: "18:00 PKT · London closing, New York open",
  next: "Next: Morning Edition, 08:00 PKT",
  todayKey: "Tue",
  kicker: "Oil tumbles below $98 as Gulf barrels flood back and OPEC+ holds November steady · the dollar eases and long yields slip, so gold and silver turn higher · US trade deficit widens to its biggest since March 2025 · all eyes on tomorrow's Fed minutes",
  headline: "Oil slides below $98 as <em>Gulf barrels flood back</em> — dollar eases, metals turn up",
  dek: "The afternoon flipped the morning's script. Crude, which had only slipped at midday, fell hard through the European close and into the New York open: Brent dropped about 2.8% to roughly $97.55 and WTI about 2% to $87.63, both at their lowest in two weeks. The supply side simply overwhelmed the Gulf risk headlines. Saudi Arabia's East-West pipeline is back to about 5.5 million barrels a day, regional crude exports have climbed past 80% of pre-war levels and actually topped them on some late-September days, Saudi Arabia cut its November Arab Light price to Asia by $3 a barrel — the lowest in six years — and OPEC+ agreed over the weekend to leave November output targets unchanged. The G7's 100-million-barrel reserve release, diesel-heavy in its first 20 days, still hangs over the market. Houthi claims of a strike on the Aramco refinery at Rabigh stayed unverified and did little to lift prices, though Aramco's CEO warned the world's spare-supply buffer is running 'scarily thin.' With oil falling, the inflation fear that drove this morning's bond selloff eased: the 10-year yield slipped to about 5.28% from its 24-year high and the dollar index fell 0.3% to around 101.85, pressured further by a US trade deficit that widened to $105.6 billion in August, the biggest since March 2025 and wider than the $102 billion expected. A softer dollar and steadier yields finally gave the metals room — gold turned up about 0.6% to near $4,167 and silver firmed 0.3% to about $61.33. Bitcoin and ether stayed boxed near $85,500 and $2,705, waiting on Wednesday's FOMC minutes.",
  verdict: [
    ["Oil","Recovering Gulf exports, a steady OPEC+ and a Saudi price cut overwhelm the strike risk","down","Softer"],
    ["Nat gas","EU TTF jumps on thin storage and Hormuz risk; US HH firm on cooler forecasts","up","Firm (EU)"],
    ["Gold","Turning up as the dollar eases and yields slip off the highs","flat","Steadier"],
    ["Silver","Firming off two-month lows; still the year's best performer","flat","Steadier"],
    ["Dollar","Easing as oil falls, yields slip and the trade gap widens","down","Softer"],
    ["BTC / ETH","Boxed in ahead of the Fed minutes; yields still the drag","flat","Range-bound"]
  ],
  assets: [
    {id:"brent",nm:"Brent crude",px:97.55,dp:2,pre:"$",u:"per barrel · Dec (front month)",d:-2.76,m:0.40,y:49.05,tag:"oil",note:"Fell ~2.8% to a two-week low; recovering Gulf exports, steady OPEC+ and a Saudi price cut sink the risk premium"},
    {id:"wti",nm:"WTI crude",px:87.63,dp:2,pre:"$",u:"per barrel · Nov",d:-2.01,m:-5.80,y:41.96,tag:"oil",note:"Dropped below $88; East-West pipeline back near 5.5 mb/d, Brent-WTI gap near $10"},
    {id:"hh",nm:"US nat gas (HH)",px:3.07,dp:2,pre:"$",u:"per MMBtu",d:0.09,m:5.24,y:-12.27,tag:"gas",note:"Firm near $3.07 on cooler Oct 12-15 forecasts; record Lower-48 output caps it year-on-year"},
    {id:"ttf",nm:"EU gas (TTF)",px:76.05,dp:2,pre:"€",u:"per MWh",d:3.45,m:3.75,y:128.75,tag:"gas",note:"Jumped ~3.5%; EU storage thin, Qatar force majeure, LNG flows still well below pre-war despite a Hormuz rebound"},
    {id:"gold",nm:"Gold",px:4166.79,dp:2,pre:"$",u:"per troy oz · spot",d:0.65,m:-5.41,y:4.54,tag:"metals",note:"Turned up ~0.6% to near $4,167 as the dollar eased and yields slipped off 24-year highs"},
    {id:"silver",nm:"Silver",px:61.33,dp:2,pre:"$",u:"per troy oz",d:0.29,m:-7.42,y:28.02,tag:"metals",note:"Firmed off two-month lows near $61; still up ~28% on the year, the standout of the complex"},
    {id:"btc",nm:"Bitcoin",px:85549,dp:0,pre:"$",u:"approx. spot",d:-0.28,m:8.15,y:-29.55,tag:"crypto",note:"Boxed near $85.5k; ETF outflows and liquidations keep it range-bound into the Fed minutes"},
    {id:"eth",nm:"Ether",px:2705,dp:0,pre:"$",u:"approx. spot",d:-0.22,m:8.62,y:-39.23,tag:"crypto",note:"Near $2,705; holding monthly gains, the stronger of the two"}
  ],
  extraTape: [["US 10Y","~5.28%","−3bp; off 24-yr high"],["US 2Y","~4.80%","short end eases"],["US 30Y","~5.65%","long end still leads"],["DXY","~101.85","−0.31%; softer with oil"],["Fed funds","3.75–4.00%","Oct hold ~78%"],["EUR/USD","~1.122","steadier vs dollar"],["USD/JPY","~158.2","+0.16%; intervention watch"],["US trade gap","−$105.6B","Aug; widest since Mar 2025"],["OPEC+","Nov steady","output targets held"],["G7","100m bbl release","crude + diesel"]],
  chain: [
    ["Gulf exports keep recovering","East-West pipeline back near 5.5 mb/d; Saudi cuts Asian prices to a 6-year low.","exports >80% pre-war"],
    ["OPEC+ holds November","Saudi Arabia, Russia and five others leave output targets unchanged.","no new cut"],
    ["G7 release looms","100m barrels of crude and diesel set to flow over four months.","diesel-heavy first"],
    ["Oil tumbles","Supply overwhelms the Rabigh strike headlines; Brent below $98.","WTI ~$87.6"],
    ["Yields and dollar ease","Lower oil cools inflation fear; the trade gap widens.","10Y ~5.28%, DXY ~101.9"],
    ["Metals turn up","A softer dollar and slipping yields finally give gold and silver room.","Gold ~$4,167"]
  ],
  stories: [
    {tag:"oil",tags:["Brent","WTI","OPEC+","Saudi"],impact:4,
     h:"Oil tumbles below $98 as Gulf barrels flood back",
     happened:"<p>What was a soft session at midday became a rout by the New York open. Brent fell about 2.8% to roughly $97.55 and WTI about 2% to $87.63, both at two-week lows. The supply side won decisively: Saudi Arabia's East-West pipeline is flowing again at about 5.5 million barrels a day after its mid-September shutdown, regional crude exports excluding Iran have climbed past 80% of pre-war levels — and topped them on several late-September days, per shipping data — and Saudi Arabia cut its November Arab Light price to Asia by $3 a barrel, the lowest in six years. OPEC+ had already agreed over the weekend to leave November output targets unchanged. The G7's 100-million-barrel reserve release, front-loaded with diesel, still looms.</p><p>Against all that, Houthi claims of a strike on the Aramco refinery at Rabigh stayed unverified and barely registered. Seven vessel attacks have been reported near the Strait of Hormuz since 28 September, and a tanker was hit by an unknown projectile on Sunday, but the crew was safe and flows held.</p>",
     why:"<p>This is the market pricing physical barrels over headlines, and doing it with conviction. A refinery claim and tanker incidents would normally add a premium; instead, recovering exports, a steady OPEC+ and Saudi discounting pulled Brent through $100 and toward $97. The risk premium is capped, not gone — a verified, lasting hit to an export node is the thing that would flip it (analysis).</p>",
     why_note:"",
     days:"<ul><li>API inventories land ~01:30 PKT Wednesday and the EIA report at 19:30 PKT; watch diesel stocks for the first sign the G7 barrels are arriving (analysis).</li><li>Brent support $97 then $95, resistance $100; WTI support $87 (analysis).</li></ul>",
     months:"<ul><li>US officials have floated possible strikes on Iran after the 3 November vote, which would put a Gulf premium back in play into year-end (analysis).</li></ul>",
     src:[0,1,14,15,16,18]},
    {tag:"rates",tags:["Trade","Dollar","Data"],impact:3,
     h:"US trade deficit widens to $105.6B, the biggest since March 2025",
     happened:"<p>The US data at 17:30 PKT came in soft for the dollar. The August trade deficit widened to $105.6 billion, more than the $102 billion expected and the largest gap since March 2025, driven by a surge in imports to $420.8 billion. It followed an advance goods reading that had already flagged a sharp widening. The dollar index, already easing with oil, slipped 0.3% to about 101.85.</p>",
     why:"<p>A wider trade gap is a small drag on the dollar and feeds the soft-growth story that is pulling at the long end of the Treasury curve. For commodities, a softer dollar is the clearest near-term tailwind — it is a big part of why gold and silver turned up this afternoon.</p>",
     days:"<ul><li>Wednesday's FOMC minutes and the 10-year auction are the next dollar tests; weak demand or hawkish minutes would steady the greenback (analysis).</li></ul>",
     months:"<ul><li>Persistent twin deficits and a Fed near the end of its hikes are a medium-term headwind for the dollar, and a tailwind for dollar-priced metals (analysis).</li></ul>",
     src:[11,7]},
    {tag:"metals",tags:["Gold","Silver","Dollar"],impact:3,
     h:"Gold and silver turn up as the dollar eases",
     happened:"<p>After two weeks of pressure, the metals finally caught a bid. Spot gold rose about 0.6% to near $4,167, and silver firmed 0.3% to about $61.33, bouncing off two-month lows. Both are still down on the month — gold about 5.4%, silver about 7.4% — but silver remains up roughly 28% on the year, the standout of the complex on industrial and solar demand.</p>",
     why:"<p>The move is straight off the dollar and yields: with the dollar index down 0.3% and the 10-year slipping from its 24-year high, the two forces that had been capping the metals eased at once. Safe-haven buying on the Gulf headlines is a secondary support. A lasting recovery, though, still probably needs yields to peak.</p>",
     days:"<ul><li>Gold: support $4,100, resistance $4,226 (Friday's high) (analysis).</li><li>Silver: hold above $60; next resistance near $62.5 (analysis).</li></ul>",
     months:"<ul><li>If the Fed signals it is done after October, that would likely be the trigger for a firmer leg in gold (analysis).</li></ul>",
     src:[2,3,21]},
    {tag:"oil",tags:["OPEC+","Aramco","Supply"],impact:3,
     h:"OPEC+ holds November steady; Aramco warns buffer is 'scarily thin'",
     happened:"<p>Seven OPEC+ members, including Saudi Arabia and Russia, agreed to keep November production targets unchanged rather than add or cut barrels — a hold that, with Gulf exports recovering, leaves the market well supplied in the near term. Yet Aramco's chief executive warned that the world's spare-supply buffer is running 'scarily thin,' a reminder of how little cushion there is if a real outage hits.</p>",
     why:"<p>The two messages aren't contradictory: plenty of oil is reaching the market right now, but the margin for error is slim. That tension is exactly why oil can fall on recovering exports today and still carry a sharp upside risk if a Gulf export node goes down.</p>",
     days:"<ul><li>This week's OPEC monthly report will update the group's read on balances after the November hold (analysis).</li></ul>",
     months:"<ul><li>A thin buffer means any lasting disruption — Hormuz, Rabigh or Iran — would move prices faster than usual (analysis).</li></ul>",
     src:[16,17]},
    {tag:"gas",tags:["Nat gas","Europe","LNG"],impact:3,
     h:"Europe's gas jumps again as winter nears with thin stocks",
     happened:"<p>EU gas (TTF) rose about 3.5% to near €76.05/MWh and is up more than 120% on the year. European storage remains below the five-year norm, QatarEnergy's force majeure on Italian deliveries runs through December, and LNG flows are still well below pre-war levels even after a rebound in cargoes squeezing through the Strait of Hormuz. US Henry Hub is firm near $3.07/MMBtu, up about 5.2% on the month as forecasts turn cooler for 12-15 October, though record Lower-48 output keeps it down year-on-year.</p>",
     why:"<p>Europe heads into winter with thin stocks and constrained LNG. More cargoes slipping through the Gulf eases the pinch at the margin, but with storage this low, any Hormuz or Qatar supply news still moves TTF first and fastest.</p>",
     days:"<ul><li>Thursday 19:30 PKT: EIA natural gas storage; another below-normal build would support Henry Hub.</li><li>TTF stays headline-driven on any Hormuz or Qatar supply news.</li></ul>",
     months:"<ul><li>A cold early winter with storage this low could push TTF sharply higher (analysis).</li></ul>",
     src:[4,5,19]},
    {tag:"rates",tags:["Yields","Treasuries","FOMC"],impact:3,
     h:"Yields slip but hold near 24-year highs into the Fed minutes",
     happened:"<p>The Treasury selloff that drove the morning eased as oil fell. The 10-year yield slipped about 3 basis points to around 5.28%, just off its 24-year high; the 30-year sits near 5.65% and the 2-year near 4.80%. The 10-year is still up roughly half a point on the month even as weak jobs data pinned the odds of an October hike at about 78% for a hold.</p>",
     why:"<p>Lower oil cools the inflation fear that had been lifting the long end, so yields backed off. But sticky inflation and heavy Treasury issuance keep the floor high — this is a pause in the selloff, not a reversal, and the Fed minutes could reset it either way.</p>",
     days:"<ul><li>Wednesday: FOMC minutes (15-16 Sep) at 23:00 PKT and the 10-year auction at 22:01 PKT; weak bidding or hawkish minutes would push yields back up (analysis).</li></ul>",
     months:"<ul><li>Yields likely need a clear Fed 'we're done' signal to peak; until then the long-end story has room to run (analysis).</li></ul>",
     src:[6,20]},
    {tag:"crypto",tags:["Bitcoin","Ether","Rates"],impact:2,
     h:"Bitcoin and ether stay boxed ahead of the Fed minutes",
     happened:"<p>Bitcoin held near $85,549, off about 0.3% on the day but still up roughly 8.2% on the month. Ether was near $2,705, down about 0.2% and up about 8.6% on the month, the stronger of the two. ETF outflows and a round of liquidations have kept both range-bound in the $84,000-88,000 zone as traders wait on Wednesday's FOMC minutes.</p>",
     why:"<p>The afternoon's softer dollar is a mild help, but with yields still above 5% pulling money toward cash and bonds, risk appetite stays thin. Sellers hold the $86,000-88,000 zone.</p>",
     days:"<ul><li>Support $82,000; resistance $88,000, then $90,000 (analysis).</li></ul>",
     months:"<ul><li>A break above $88,000 would point to a wider recovery; below $82,000 opens $74,000-78,000 (analysis).</li></ul>",
     src:[10,22]}
  ],
  calendar: [
    {k:"Tue",d:"6 Oct",ev:[
      {t:"Done",n:"US trade balance (Aug)",c:"−$105.6B vs −$102B exp · widest since Mar 2025",i:"m",x:"A wider gap added to the dollar's slide and the soft-growth story pulling at long yields."},
      {t:"Done",n:"New York open · oil rout",c:"Brent below $98 · dollar eases · metals turn up",i:"h",x:"Recovering Gulf exports and a steady OPEC+ sank crude; gold and silver caught a bid as the dollar softened."},
      {t:"~01:30 Wed",n:"API oil inventories",c:"Weekly, private",i:"m",x:"First read on US crude and diesel stocks; sets up the EIA report."}]},
    {k:"Wed",d:"7 Oct",ev:[
      {t:"19:30",n:"EIA weekly oil report",c:"Crude, gasoline, distillates",i:"m",x:"Diesel stocks show whether the G7 release is reaching the market."},
      {t:"22:01",n:"US 10-year Treasury auction",c:"Demand test",i:"m",x:"Weak demand would push yields back toward their highs."},
      {t:"23:00",n:"FOMC minutes (15-16 Sep)",c:"After the Sept hike",i:"h",x:"Shows how many officials want more hikes; the week's main event."}]},
    {k:"Thu",d:"8 Oct",ev:[
      {t:"16:30",n:"ECB meeting accounts",c:"Sept meeting",i:"m",x:"The other side of the dollar-euro divergence trade."},
      {t:"17:30",n:"US jobless claims",c:"Exp. ~200k",i:"m",x:"A rise would add to the case for a pause."},
      {t:"19:30",n:"EIA natural gas storage",c:"Weekly injection",i:"m",x:"Another below-normal build would support Henry Hub."},
      {t:"22:01",n:"US 30-year Treasury auction",c:"Demand test",i:"h",x:"Long-end demand is key for gold."}]},
    {k:"Fri",d:"9 Oct",ev:[
      {t:"17:30",n:"Canada jobs (Sep)",c:"Exp. +9.5k; UE 6.5%",i:"m",x:"Moves CAD and oil-linked FX."},
      {t:"19:00",n:"UMich sentiment (Oct prelim)",c:"Exp. ~48",i:"m",x:"Inflation expectations matter most for the Fed."}]},
    {k:"Mon",d:"12 Oct",ev:[
      {t:"All day",n:"Columbus Day (US)",c:"Bond market closed; stocks open",i:"m",x:"Thin Treasury liquidity; watch equities and oil for direction."},
      {t:"This wk",n:"OPEC monthly report",c:"Demand/supply outlook",i:"m",x:"OPEC's read on balances after the November hold."}]}
  ],
  later: [["28 Oct","FOMC decision · hold ~78% priced"],["29-30 Oct","Bank of Japan meeting"],["1 Nov","OPEC+ meeting · December targets"],["3 Nov","US midterm elections · strikes on Iran seen possible after"],["Jan","G7 reserve release runs about four months"]],
  scenarios: [
    {id:"deal",nm:"Talks restart",sub:"Iran and the US narrow gaps; Houthi strikes ebb and Gulf traffic fully normalizes",
     m:{Oil:"dn2",Gas:"dn",Gold:"up",Silver:"up",Dollar:"dn",Yields:"dn",BTC:"up",ETH:"up"},
     why:"With exports already past 80% of pre-war levels and reserve barrels on the way, real de-escalation would knock more off oil. Lower oil would pull yields and the dollar down further — the best setup for the metals and crypto, which only just turned up as those two eased today."},
    {id:"stall",nm:"Stalemate",sub:"Base case: tit-for-tat Gulf strikes but no big outage, Fed holds in October",
     m:{Oil:"fl",Gas:"up",Gold:"fl",Silver:"fl",Dollar:"fl",Yields:"fl",BTC:"fl",ETH:"fl"},
     why:"Brent settles into a $95-100 range as recovering exports offset strike risk. Long yields hold near their highs on inflation and issuance even as hike odds fall, so the dollar steadies and gold trades sideways after today's bounce. EU gas keeps firming into winter."},
    {id:"esc",nm:"Gulf escalation",sub:"Rabigh damage proves real or a major export node is hit",
     m:{Oil:"up2",Gas:"up2",Gold:"up",Silver:"dn",Dollar:"up",Yields:"up",BTC:"dn",ETH:"dn"},
     why:"If the Rabigh claim is verified as a real outage or an export terminal is struck, oil and gas could spike despite the G7 barrels — and with the buffer 'scarily thin,' fast. Higher oil feeds the bond selloff; gold gains on haven demand, while silver and crypto likely fall with risk."}
  ],
  levels: [
    ["Brent (Dec)","$95 · $97.5 · $100","Support; spot; resistance."],
    ["WTI","$87 · $87.6 · $90","Support; spot; resistance."],
    ["Gold","$4,100 · $4,167 · $4,226","Support; spot; Friday's high."],
    ["Silver","$60 · $61.3 · $62.5","Floor; spot; next resistance."],
    ["US 10Y","5.20% · 5.28% · 5.33%","Support; spot; 24-year high."],
    ["US 30Y","5.60% · 5.65% · 5.75%","Leader of the long-end selloff."],
    ["DXY","101.5 · 101.85 · 102.5","Support; spot; resistance that caps metals."],
    ["EUR/USD","1.117 · 1.122 · 1.125","Range the euro is holding."],
    ["USD/JPY","158 · 160","Watch; Tokyo intervention zone."],
    ["Bitcoin","$82k · $88k","Support; resistance."]
  ],
  wire: [
    {d:"5 Oct",tag:"Gas",h:"LNG Trade Through Hormuz Extends Rebound Despite Shipping Risks",url:"https://www.bloomberg.com/news/articles/2026-10-05/lng-trade-through-hormuz-extends-rebound-despite-shipping-risks",why:"More cargoes are squeezing through the strait, easing Europe's winter pinch at the margin even as tanker risk persists."},
    {d:"5 Oct",tag:"Oil",h:"Global Oil Supply Buffer Running 'Scarily Thin,' Aramco CEO Says",url:"https://www.bloomberg.com/news/articles/2026-10-05/global-oil-supply-buffer-running-scarily-thin-aramco-ceo-says",why:"Plenty of oil is flowing now, but the cushion is slim — which is why today's selloff still carries sharp upside risk."},
    {d:"5 Oct",tag:"Oil",h:"Saudis Cut Flagship Oil Price to Asia to Lowest in Six Years",url:"https://www.bloomberg.com/news/articles/2026-10-05/saudis-cut-flagship-oil-price-to-asia-to-lowest-in-six-years",why:"The $3 cut to Arab Light for Asia is a loud supply signal, pulling hard against the Gulf risk premium."},
    {d:"5 Oct",tag:"Gold",h:"Gold Steadies as Stronger Dollar and Yields Weigh on Rate Path",url:"https://www.bloomberg.com/news/articles/2026-10-05/gold-steadies-as-stronger-dollar-and-yields-weigh-on-rate-path",why:"Sets up today's turn: once the dollar and yields eased, the two forces capping gold loosened at once."},
    {d:"2 Oct",tag:"Rates",h:"Bond Traders Cut Fed Rate Hike Bets After Weak US Jobs Report",url:"https://www.bloomberg.com/news/articles/2026-10-02/bond-traders-pull-back-on-fed-hike-bets-after-soft-jobs-data",why:"Soft jobs put October's hold near 78% — the backdrop for Wednesday's minutes and every rate-sensitive market."},
    {d:"2 Oct",tag:"Dollar",h:"Dollar Falls as Traders Pare Fed-Hike Bets After Soft Jobs Data",url:"https://www.bloomberg.com/news/articles/2026-10-02/dollar-falls-as-traders-pare-fed-hike-bets-after-soft-jobs-data",why:"The dollar's softer tone, extended by today's wide trade gap, is the clearest near-term tailwind for the metals."}
  ],
  sources: [
    ["Trading Economics · Brent crude","https://tradingeconomics.com/commodity/brent-crude-oil"],
    ["Trading Economics · WTI crude","https://tradingeconomics.com/commodity/crude-oil"],
    ["Trading Economics · Gold","https://tradingeconomics.com/commodity/gold"],
    ["Trading Economics · Silver","https://tradingeconomics.com/commodity/silver"],
    ["Trading Economics · EU natural gas","https://tradingeconomics.com/commodity/eu-natural-gas"],
    ["Trading Economics · US natural gas","https://tradingeconomics.com/commodity/natural-gas"],
    ["Trading Economics · US 10Y yield","https://tradingeconomics.com/united-states/government-bond-yield"],
    ["Trading Economics · US dollar index","https://tradingeconomics.com/united-states/currency"],
    ["Trading Economics · EUR/USD","https://tradingeconomics.com/euro-area/currency"],
    ["Trading Economics · USD/JPY","https://tradingeconomics.com/japan/currency"],
    ["Trading Economics · Crypto","https://tradingeconomics.com/crypto"],
    ["Trading Economics · US balance of trade","https://tradingeconomics.com/united-states/balance-of-trade"],
    ["Fortune · Current price of silver, Oct 6 2026","https://fortune.com/article/current-price-of-silver-10-6-2026"],
    ["Yahoo Finance · Gold price today, Oct 6 2026","https://finance.yahoo.com/personal-finance/investing/article/gold-price-today-tuesday-october-6-2026-gold-edges-higher-as-investors-monitor-domestic-and-global-conditions-111213149.html"],
    ["Business Recorder · Oil slips as Mideast exports, G7 stockpile ease supply concerns","https://www.brecorder.com/news/40442853/oil-slips-as-mideast-exports-g7-stockpile-ease-supply-concerns"],
    ["WION · Oil prices fall ~2% as G7 release offsets Hormuz fears","https://www.wionews.com/world/oil-prices-fall-by-almost-2-as-g7-stockpile-release-offsets-strait-of-hormuz-supply-fears-1791260713210"],
    ["Bloomberg · OPEC+ agrees to keep output steady in November","https://www.bloomberg.com/news/articles/2026-10-04/opec-has-deal-outline-for-steady-november-quotas-delegates-say"],
    ["Bloomberg · Global oil supply buffer running 'scarily thin,' Aramco CEO says","https://www.bloomberg.com/news/articles/2026-10-05/global-oil-supply-buffer-running-scarily-thin-aramco-ceo-says"],
    ["Bloomberg · Saudis cut flagship oil price to Asia to lowest in six years","https://www.bloomberg.com/news/articles/2026-10-05/saudis-cut-flagship-oil-price-to-asia-to-lowest-in-six-years"],
    ["Bloomberg · LNG trade through Hormuz extends rebound despite shipping risks","https://www.bloomberg.com/news/articles/2026-10-05/lng-trade-through-hormuz-extends-rebound-despite-shipping-risks"],
    ["Bloomberg · Bond traders cut Fed rate hike bets after weak US jobs report","https://www.bloomberg.com/news/articles/2026-10-02/bond-traders-pull-back-on-fed-hike-bets-after-soft-jobs-data"],
    ["Bloomberg · Gold steadies as stronger dollar and yields weigh on rate path","https://www.bloomberg.com/news/articles/2026-10-05/gold-steadies-as-stronger-dollar-and-yields-weigh-on-rate-path"],
    ["CryptoTimes · Bitcoin holds $85,500 as outflows hit before Fed minutes","https://cryptotimes.io/2026/10/06/bitcoin-price-today-btc-holds-85500-as-172m-liquidations-etf-outflows-hit-before-fed-minutes"]
  ]
};
/* evening build 2026-10-06T18:00:00+05:00 PKT */
/* ===== END EDITION DATA ===== */
