/* ===== EDITION DATA — each edition replaces this block ===== */
const EDITION = {
  name: "Midday Edition",
  date: "Thursday, 1 October 2026",
  pressTime: "12:00 PKT · after the Asia session, into the London open",
  next: "Next: Evening Edition, 18:00 PKT",
  todayKey: "Thu",
  kicker: "Since the Morning Edition · Asia session · BOJ opinions · Goldman Fed call · London open",
  headline: "Gold bounces and the <em>yen slides</em> past 158 as Fed hike bets cool; oil flat near $98",
  dek: "The main change since 08:00 PKT is in metals and the yen. Gold has climbed about 0.8% to near $4,189 and silver 1.4% to $61.23, after Goldman Sachs moved its call for the next Fed hike from October to December and New York Fed President John Williams said there is no urgency. The yen fell about 0.6% to 158.4 per dollar because the Bank of Japan's meeting summary gave no clear signal of a quick second hike. The Nikkei rose about 2.5% on chip stocks after Micron's strong results. Oil barely moved in Asia: Brent is near $98 and WTI near $90.50, as better Hormuz flows offset stalled US–Iran talks. European gas slipped 1% to €71.63. Bitcoin is near $84,200 and ether near $2,713. US 10-year yields are holding near 5.30% as Europe opens.",
  verdict: [
    ["Oil","Flat in Asia; recovering Gulf flows offset stalled Iran talks","flat","Steady"],
    ["Nat gas","TTF gives back 1% to €71.6; Henry Hub slips under $3","down","Softer"],
    ["Gold","Back near $4,190 as October hike bets fade","up","Bounce"],
    ["Silver","Up 1.4% to $61.2, off its near two-month low","up","Bounce"],
    ["Dollar","Strong against the yen past 158; flat against the euro","up","Firm"],
    ["BTC / ETH","Bitcoin $84.2k, ether $2.7k; small gains, ETF outflows","flat","Range"]
  ],
  assets: [
    {id:"brent",nm:"Brent crude",px:98.07,dp:2,pre:"$",u:"per barrel · Dec (front month)",d:-0.01,m:null,y:52.89,tag:"oil",note:"Flat through the Asia session; 1M % not shown because sources disagree after the contract roll"},
    {id:"wti",nm:"WTI crude",px:90.48,dp:2,pre:"$",u:"per barrel · Nov",d:0.06,m:-0.59,y:49.60,tag:"oil",note:"Back above $90 after dipping below it early in Asia"},
    {id:"hh",nm:"US nat gas (HH)",px:2.98,dp:2,pre:"$",u:"per MMBtu",d:-1.59,m:0.74,y:-13.48,tag:"gas",note:"Below $3 after four losing sessions; mild weather, high storage"},
    {id:"ttf",nm:"EU gas (TTF)",px:71.63,dp:2,pre:"€",u:"per MWh",d:-1.00,m:-2.72,y:127.73,tag:"gas",note:"Gives back part of Wednesday's 4% jump; storage 71% vs 87% normal"},
    {id:"gold",nm:"Gold",px:4189,dp:0,pre:"$",u:"per troy oz",d:0.76,m:-4.52,y:8.64,tag:"metals",note:"Up about $30 since the morning, from lows near $4,140"},
    {id:"silver",nm:"Silver",px:61.23,dp:2,pre:"$",u:"per troy oz",d:1.37,m:-6.25,y:30.31,tag:"metals",note:"Back above $61 after a ~6% monthly fall"},
    {id:"btc",nm:"Bitcoin",px:84213,dp:0,pre:"$",u:"approx. spot",d:0.9,m:null,y:null,tag:"crypto",note:"Up ~0.9% in 24h; resistance $84.8k–85.8k"},
    {id:"eth",nm:"Ether",px:2713,dp:0,pre:"$",u:"approx. spot",d:1.3,m:null,y:null,tag:"crypto",note:"Up ~1.3% in 24h despite ETF outflows"}
  ],
  extraTape: [["US 10Y","~5.30%","+1bp; near highest since 2002"],["US 30Y","~5.64%","highest since 2002"],["DXY","101.61","+0.16%; near Apr 2025 high"],["Fed funds","3.75–4.00%","Oct hike odds ~38–40%"],["EUR/USD","1.1325","−0.04%; near lowest since May 2025"],["USD/JPY","158.37","+0.6% after BOJ summary"],["Nikkei 225","+2.5%","chip stocks lead after Micron"],["S&P 500 fut.","+0.3%","Nasdaq fut. +0.5% (Asia trade)"]],
  chain: [
    ["Goldman moves its call","Next Fed hike now seen in December, not October.","Wed night"],
    ["Fed says no rush","Williams: no urgency after the September hike.","Odds ~38–40%"],
    ["Metals bounce","Gold up ~0.8%, silver up ~1.4% in Asia.","$4,189 · $61.23"],
    ["BOJ gives no date","Summary keeps hikes coming, but no quick second one.","Yen −0.6%"],
    ["Asian chips rally","Nikkei +2.5% on Micron's beat and guidance.","KOSPI +0.6–0.9%"],
    ["Oil stays put","Hormuz flows ~13.2m b/d vs stalled US–Iran talks.","Brent ~$98"]
  ],
  stories: [
    {tag:"metals",tags:["Gold","Silver","Fed"],impact:5,
     h:"Gold climbs back toward $4,190 as Goldman pushes its Fed hike call to December",
     happened:"<p>Gold has risen about 0.8% to near $4,189 an ounce, up about $30 since the Morning Edition and well above its Asia low near $4,140. Silver is up about 1.4% at $61.23. Both are still down for the month: gold about 4.5% and silver about 6%.</p><p>Overnight, Goldman Sachs moved its forecast for the next Fed rate hike from October to December, after the soft PCE report and comments from New York Fed President John Williams that there is no urgency to move again after September's hike.</p>",
     why:"<p>Fewer near-term hike bets help gold, which pays no interest. Markets now put October hike odds at about 38–40%, down from about 51% before the PCE data. But 10-year yields near 5.30% and a firm dollar still hold gold back, so this looks like a bounce, not a new trend. Bloomberg also describes gold as steady on the softer inflation data.</p>",
     days:"<ul><li>Today 19:00 PKT: ISM manufacturing prices. A hot number could erase today's gain (analysis).</li><li>Friday 17:30 PKT: US jobs report is the main test for $4,200.</li></ul>",
     months:"<ul><li>If the Fed hikes once more in December and then stops, gold could recover as yields peak (analysis).</li></ul>",
     src:[2,12,22]},
    {tag:"rates",tags:["Yen","BOJ","Japan"],impact:4,
     h:"Yen slides past 158 as BOJ summary gives no date for the next hike",
     happened:"<p>USD/JPY is near 158.37, up about 0.6% on the day. The yen had been the strongest G-10 currency on Wednesday. The Bank of Japan's Summary of Opinions from its 17–18 September meeting, when it raised rates to 1.25% on a 7–2 vote, said the focus has moved from lifting inflation to keeping it near 2%. Some members said the bank could speed up if prices overshoot.</p><p>Bloomberg reports the summary reduced bets on a back-to-back hike in October. The Nikkei 225 rose about 2.5%, led by chip stocks.</p>",
     why:"<p>The BOJ still plans to keep raising rates, but traders now see no hurry. With US yields above 5.3%, the rate gap keeps pushing the yen lower. A weak yen raises Japan's import bill for oil and LNG, which is one reason officials keep warning about intervention.</p>",
     days:"<ul><li>The 158–160 zone is where Tokyo's warnings have turned into action before (analysis).</li><li>A weak US jobs report on Friday would likely pull USD/JPY lower.</li></ul>",
     months:"<ul><li>The October BOJ meeting depends on wage and price data; a hike there would support the yen (analysis).</li></ul>",
     src:[7,13,14,20,21]},
    {tag:"rates",tags:["Fed","Yields","Dollar"],impact:4,
     h:"Fed officials signal patience, but long yields stay near 2002 highs",
     happened:"<p>Williams said one more hike this year may be enough and the Fed should wait for more data. Minneapolis Fed President Neel Kashkari said inflation is still too high at around 3% and pencilled in one more hike this year and another in 2027.</p><p>The 10-year Treasury yield is near 5.30%, up about 1 basis point, and the 30-year near 5.64%. The dollar index is near 101.61, up 0.16%. US stock futures rose in Asia trade: S&P 500 futures about +0.3% and Nasdaq futures about +0.5%.</p>",
     why:"<p>The 10-year yield has risen about 67 basis points since late August. That rise already tightens financial conditions, which is one reason the Fed may not need to hike in October. But strong growth, oil near $100 and heavy government borrowing keep long yields high.</p>",
     days:"<ul><li>Today 17:30 PKT jobless claims and 19:00 PKT ISM manufacturing.</li><li>Friday's payrolls decide whether October hike odds fall below 30% (analysis).</li></ul>",
     months:"<ul><li>Base case: one more Fed hike, in December; long yields stay above 5% while oil stays high (analysis).</li></ul>",
     src:[6,5,12,14,15,16]},
    {tag:"oil",tags:["Oil","Iran","Hormuz","OPEC+"],impact:4,
     h:"Oil flat through Asia as better Hormuz flows offset stalled Iran talks",
     happened:"<p>December Brent is near $98.07 and November WTI near $90.48, almost unchanged since the morning. Brent gained about 14% in September. Flows through the Strait of Hormuz are estimated at about 13.2 million barrels a day, and Gulf exports at about 23.3 million barrels a day, close to pre-war levels.</p><p>The US State Department called Iran's letter to Americans 'an act of desperation'. This follows the US sending Iran's UN delegation home early on Wednesday. US crude stocks rose by 922,000 barrels last week to 427.3 million.</p>",
     why:"<p>Supply is recovering, but without a peace deal the recovery can be reversed quickly. Trump has also denied reports that sanctions relief is being discussed. That keeps a risk premium in prices while flows improve.</p>",
     days:"<ul><li>Sunday: OPEC+ meets and is expected to keep November targets unchanged.</li><li>Brent support $95, resistance $100 (analysis).</li></ul>",
     months:"<ul><li>If flows keep improving and no new attacks happen, Brent could drift toward the low $90s by year-end (analysis).</li></ul>",
     src:[0,1,9,10,11,24]},
    {tag:"gas",tags:["Nat gas","Europe","LNG"],impact:3,
     h:"European gas gives back 1%; US gas stays under $3",
     happened:"<p>EU gas (TTF) is near €71.63/MWh, down about 1%, after Wednesday's 4% gain. It is still more than double its level a year ago. US Henry Hub is near $2.98/MMBtu, down about 1.6%, after four losing sessions.</p>",
     why:"<p>EU storage is about 71% full against a normal 87%, and Germany's is just above 57%. QatarEnergy has extended its LNG force majeure through December, Bloomberg reports. Weaker Chinese buying is the main relief. In the US, mild weather and storage 2.4% above normal keep prices low, even with LNG exports near 17.9 bcf a day.</p>",
     days:"<ul><li>Today 19:30 PKT: EIA gas storage.</li><li>Hormuz headlines remain the main driver for TTF.</li></ul>",
     months:"<ul><li>A cold start to winter with storage this low could send TTF sharply higher (analysis).</li></ul>",
     src:[3,4,23]},
    {tag:"rates",tags:["Europe","Euro","Stocks"],impact:3,
     h:"Europe opens after its worst month since March; euro near its lowest since May 2025",
     happened:"<p>The Stoxx 600 fell 0.5% on Wednesday to end its worst month since March. The Euro Stoxx 50 lost 0.83%, the DAX 0.74% and the FTSE 100 0.29%. EUR/USD is near 1.1325, little changed today, after falling more than 2% in September.</p>",
     why:"<p>The Fed is seen as more willing to hike than the ECB, whose main rate is 2.65%. Eurozone growth is slow at about 0.9% a year, and upcoming elections in France, Spain and Italy add political risk. Asian chip strength may help European tech stocks today (analysis).</p>",
     days:"<ul><li>Today 13:00 PKT: final eurozone manufacturing PMIs.</li><li>Friday 14:00 PKT: eurozone inflation flash, prior 3.2%. A hot number would support the euro.</li></ul>",
     months:"<ul><li>A break below 1.13 in EUR/USD would point to more dollar strength (analysis).</li></ul>",
     src:[8,15,17]},
    {tag:"crypto",tags:["Bitcoin","Ether","ETFs"],impact:2,
     h:"Bitcoin edges up to $84.2k despite ETF outflows",
     happened:"<p>Bitcoin is near $84,213, up about 0.9% in 24 hours, and ether near $2,713, up about 1.3%. US spot bitcoin ETFs saw $125.6 million of net outflows in the latest session and ether funds about $59.9 million. Weekly bitcoin ETF inflows are still about $2.39 billion, the largest in roughly a year.</p>",
     why:"<p>Lower Fed hike odds help, but 10-year yields near 5.3% limit the upside. Bitcoin is still above its 20-, 50- and 200-day moving averages.</p>",
     days:"<ul><li>Resistance $84.8k–85.8k; support $83k, then $82k (analysis).</li><li>Friday's jobs report will set the tone through yields.</li></ul>",
     months:"<ul><li>A lasting rally probably needs yields to stop rising (analysis).</li></ul>",
     src:[18,19]}
  ],
  calendar: [
    {k:"Thu",d:"1 Oct",ev:[
      {t:"04:50",n:"Japan Tankan (Q3)",c:"Large mfg +24 vs +25 exp. (out)",i:"m",x:"Slight miss, but firms see sticky inflation."},
      {t:"13:00",n:"Eurozone mfg PMI (final)",c:"September",i:"m",x:"A weak reading would add to pressure on the euro."},
      {t:"17:30",n:"US jobless claims",c:"Weekly",i:"m",x:"Another low reading would back the strong-jobs story."},
      {t:"19:00",n:"US ISM manufacturing (Sep)",c:"Activity & prices paid",i:"h",x:"Prices paid shows how much oil feeds into costs. Hot: yields up, gold gives back today's gain."},
      {t:"19:30",n:"EIA natural gas storage",c:"Weekly injection",i:"m",x:"A big injection keeps Henry Hub below $3."}]},
    {k:"Fri",d:"2 Oct",ev:[
      {t:"14:00",n:"Eurozone CPI flash (Sep)",c:"Prior 3.2%",i:"m",x:"A high print supports the euro."},
      {t:"17:30",n:"US nonfarm payrolls (Sep)",c:"Cons. ~+90k",i:"h",x:"Weak jobs could push October hike odds below 30% and lift gold. Strong jobs do the opposite."}]},
    {k:"Mon",d:"5 Oct",ev:[
      {t:"Open",n:"OPEC+ decision (Sunday) priced in",c:"Nov targets expected unchanged",i:"m",x:"A surprise or weekend Iran news would gap prices at the Asia open."},
      {t:"19:00",n:"US ISM services (Sep)",c:"Services activity & prices",i:"m",x:"Sticky services prices support the Fed hawks."}]},
    {k:"Tue",d:"6 Oct",ev:[
      {t:"21:00",n:"SPR exchange bids due",c:"Up to 40m barrels",i:"m",x:"Strong bidding means more crude flowing soon, which weighs on WTI."}]},
    {k:"Wed",d:"7 Oct",ev:[
      {t:"19:30",n:"EIA weekly oil report",c:"Crude, gasoline, distillates",i:"m",x:"Another diesel draw would keep crude supported."}]}
  ],
  later: [["4 Oct","OPEC+ online meeting · Nov targets"],["28 Oct","FOMC decision · ~38–40% hike odds; Goldman now sees December"],["3 Nov","US midterm elections · no Iran deal expected before"],["Dec","Qatar LNG force majeure runs to here"]],
  scenarios: [
    {id:"deal",nm:"Talks restart",sub:"Qatar revives talks and the two sides agree on the order of steps",
     m:{Oil:"dn2",Gas:"dn",Gold:"up",Silver:"up",Dollar:"dn",Yields:"dn",BTC:"up",ETH:"up"},
     why:"Oil loses much of its war premium. With hike bets already fading, yields and the dollar would ease. That is the best setup for gold, silver and crypto."},
    {id:"stall",nm:"Stalemate",sub:"Base case: no deal before the midterms; jobs data decides the Fed",
     m:{Oil:"fl",Gas:"fl",Gold:"up",Silver:"fl",Dollar:"fl",Yields:"mix",BTC:"fl",ETH:"fl"},
     why:"Brent stays around $95–100 as more barrels get out but talks go nowhere. With the next hike pushed toward December, gold can hold today's bounce; long yields stay near their highs."},
    {id:"esc",nm:"Escalation",sub:"Trump picks force: new US strikes or more tanker attacks",
     m:{Oil:"up2",Gas:"up2",Gold:"mix",Silver:"dn",Dollar:"up",Yields:"up",BTC:"dn",ETH:"dn"},
     why:"Crude and gas spike and Brent goes back above $100. Gold is torn between safe-haven buying and higher yields. Silver and crypto likely fall."}
  ],
  levels: [
    ["Brent (Dec)","$95 · $100","Support; round-number resistance."],
    ["WTI","$88 · $92","Support analysts watch; this week's high area."],
    ["Gold","$4,140 · $4,200","Today's Asia low; resistance it failed at on Wednesday."],
    ["Silver","$60 · $62","Round-number support; resistance."],
    ["US 10Y","5.30%","Highest since 2002 area."],
    ["US 30Y","5.65%","Break higher would add pressure on gold and stocks."],
    ["EUR/USD","1.13","Near lowest since May 2025; break opens further dollar gains."],
    ["USD/JPY","158–160","Zone where Tokyo has acted before."],
    ["Bitcoin","$83k · $85.8k","Support; top of resistance band."],
    ["EU storage","71% vs 87%","Current fill vs five-year average."]
  ],
  wire: [
    {d:"1 Oct",tag:"Dollar",h:"Yen Weakens as BOJ Summary Damps Bets for Back-to-Back Rate Hike",url:"https://www.bloomberg.com/news/articles/2026-10-01/yen-weakens-as-boj-summary-damps-bets-for-back-to-back-rate-hike",why:"Explains today's slide in the yen past 158."},
    {d:"1 Oct",tag:"Rates",h:"BOJ Summary Affirms Priority Is Preventing Inflation Overshoot",url:"https://www.bloomberg.com/news/articles/2026-10-01/boj-summary-affirms-priority-is-preventing-inflation-overshoot",why:"More BOJ hikes are still coming, just not in a hurry."},
    {d:"1 Oct",tag:"Gold",h:"Gold Steady as Softer Inflation Data Tempers Fed Rate-Hike Bets",url:"https://www.bloomberg.com/news/articles/2026-10-01/gold-steady-as-softer-inflation-data-tempers-fed-rate-hike-bets",why:"Lower hike odds are behind gold's bounce today."},
    {d:"1 Oct",tag:"Oil",h:"Latest Oil Market News and Analysis for Oct. 1",url:"https://www.bloomberg.com/news/articles/2026-09-30/latest-oil-market-news-and-analysis-for-oct-1",why:"Bloomberg's running oil blog for today's Iran and OPEC+ headlines."},
    {d:"30 Sep",tag:"Rates",h:"Asian Stocks Eye Rough Start After US Reversal: Markets Wrap",url:"https://www.bloomberg.com/news/articles/2026-09-30/stock-market-today-dow-s-p-live-updates",why:"Sets up the late US selloff that Asia then shrugged off."},
    {d:"28 Sep",tag:"Gas",h:"Qatar Extends LNG Force Majeure as Hormuz Disruptions Drag On",url:"https://www.bloomberg.com/news/articles/2026-09-28/qatar-extends-lng-force-majeure-as-hormuz-disruptions-drag-on",why:"Less Qatari LNG keeps European gas tight into winter."}
  ],
  sources: [
    ["Trading Economics · Brent crude","https://tradingeconomics.com/commodity/brent-crude-oil"],
    ["Trading Economics · WTI crude","https://tradingeconomics.com/commodity/crude-oil"],
    ["Trading Economics · Gold (and silver)","https://tradingeconomics.com/commodity/gold"],
    ["Trading Economics · EU natural gas","https://tradingeconomics.com/commodity/eu-natural-gas"],
    ["Trading Economics · US natural gas","https://tradingeconomics.com/commodity/natural-gas"],
    ["Trading Economics · US dollar index","https://tradingeconomics.com/united-states/currency"],
    ["Trading Economics · US 10Y yield","https://tradingeconomics.com/united-states/government-bond-yield"],
    ["Trading Economics · USD/JPY","https://tradingeconomics.com/japan/currency"],
    ["Trading Economics · EUR/USD","https://tradingeconomics.com/euro-area/currency"],
    ["CBS News · US–Iran live updates","https://www.cbsnews.com/live-updates/iran-war-us-negotiations-strait-of-hormuz-oil/"],
    ["Axios · Rubio ordered Iranian delegation to leave the country","https://www.axios.com/2026/10/01/rubio-iran-unga-delegation-kicked-out"],
    ["Angel One · Crude holds steady as US–Iran talks and Gulf supply assessed, 1 Oct","https://www.angelone.in/news/commodities/crude-oil-prices-hold-steady-as-us-iran-talks-and-gulf-supply-assessed-october-1-2026"],
    ["investingLive · Goldman moves next Fed hike call to December","https://investinglive.com/central-banks/goldman-sachs-moves-its-call-for-the-next-fed-rate-hike-to-december-from-october/"],
    ["investingLive · BOJ opinions show members open to faster hikes","https://investinglive.com/central-banks/boj-opinions-show-members-open-to-faster-hikes-if-inflation-risks-overshooting-2-target/"],
    ["investingLive · Asia-Pacific wrap: yen weakens, Nikkei jumps","https://investinglive.com/news/investinglive-asia-pacific-market-news-yen-weakens-nikkei-jumps/"],
    ["Saxo · Asia Market Quick Take, 1 Oct","https://www.home.saxo/en-hk/content/articles/macro/asia-market-quick-take-01-october-2026-01102026"],
    ["HDFC Sky · Global markets today, 1 Oct","https://hdfcsky.com/news/global-markets-today-october-1-2026-asian-stocks-mixed-oil-elevated-us-futures-rise-indian-markets-likely-to-open-lower"],
    ["Newsquawk · European equity opening news, 1 Oct","https://www.newsquawk.com/headlines/newsquawk-daily-european-equity-opening-news---1st-october-2026"],
    ["Analytics Insight · Crypto prices today: bitcoin steadies at $84,200","https://www.analyticsinsight.net/price-analysis/crypto-prices-today-bitcoin-steadies-at-usd-84200-as-traders-await-payrolls"],
    ["UseTheBitcoin · Bitcoin price analysis, 1 Oct","https://usethebitcoin.com/bitcoin/bitcoin-price-october-1-2026/"],
    ["Bloomberg · Yen weakens as BOJ summary damps bets for back-to-back hike","https://www.bloomberg.com/news/articles/2026-10-01/yen-weakens-as-boj-summary-damps-bets-for-back-to-back-rate-hike"],
    ["Bloomberg · BOJ summary affirms priority is preventing inflation overshoot","https://www.bloomberg.com/news/articles/2026-10-01/boj-summary-affirms-priority-is-preventing-inflation-overshoot"],
    ["Bloomberg · Gold steady as softer inflation data tempers Fed rate-hike bets","https://www.bloomberg.com/news/articles/2026-10-01/gold-steady-as-softer-inflation-data-tempers-fed-rate-hike-bets"],
    ["Bloomberg · Qatar extends LNG force majeure as Hormuz disruptions drag on","https://www.bloomberg.com/news/articles/2026-09-28/qatar-extends-lng-force-majeure-as-hormuz-disruptions-drag-on"],
    ["Reuters via 93.3 The Drive · OPEC+ set to keep output targets steady on Sunday","https://www.933thedrive.com/2026/09/30/opec-oil-producers-set-to-keep-output-targets-steady-at-sunday-meeting-sources-say/"]
  ]
};
/* ===== END EDITION DATA ===== */
