/* ===== EDITION DATA — each edition replaces this block ===== */
const EDITION = {
  name: "Evening Edition",
  date: "Friday, 2 October 2026",
  pressTime: "18:00 PKT (updated 22:00) · after the jobs report, the New York open and the European close",
  next: "Next: Morning Edition, Monday 08:00 PKT",
  todayKey: "Fri",
  kicker: "Since Thursday's Evening Edition · US jobs miss · G7 oil release · eurozone inflation 3.8% · New York open",
  headline: "Jobs miss and a <em>G7 oil release</em>: hike bets fade, WTI slips 1.5%, gold gives up its spike",
  dek: "The US added only 29,000 jobs in September against about 90,000 expected. July and August were revised down by a combined 60,000, unemployment rose to 4.2%, and pay grew just 0.1%. Traders cut the odds of an October Fed hike to roughly 12–25%, though about 80% still expect a hike by December. Treasuries rallied at first, then gave the gains back: the 10-year is near 5.27%. Gold spiked to about $4,226 on the data, then fell to near $4,137, down about 1% on the day and over 3% on the week. Oil fell after the G7 agreed to release up to 100 million barrels of crude and diesel from emergency stocks over four months. Brent is near $101.40 and WTI near $91.50. Saudi Arabia has raised flows on its key pipeline to the Red Sea to over 80% of capacity. European gas rose about 3% to €76.10 before the weekend. Eurozone inflation jumped to 3.8%. Bitcoin is near $84,500 and ether near $2,700.",
  verdict: [
    ["Oil","G7 reserve release caps rallies; China fuel halt and Hormuz keep a floor","down","Softer"],
    ["Nat gas","TTF up ~3% on weekend supply worries; Henry Hub back at $3","up","Firmer"],
    ["Gold","Faded its jobs spike; yields still near 2002 highs","flat","Choppy"],
    ["Silver","Clinging to $60; down ~10% on the month","down","Weak"],
    ["Dollar","Slightly softer after the jobs miss, but near the year's high","flat","Firm"],
    ["BTC / ETH","Bitcoin ~$84.5k, ether ~$2.7k; small moves","flat","Range"]
  ],
  assets: [
    {id:"brent",nm:"Brent crude",px:101.40,dp:2,pre:"$",u:"per barrel · Dec (front month)",d:-0.86,m:7.03,y:58.43,tag:"oil",note:"Eases after the G7 release plan; 1M/1Y % from Trading Economics at ~$102"},
    {id:"wti",nm:"WTI crude",px:91.50,dp:2,pre:"$",u:"per barrel · Nov",d:-1.48,m:0.18,y:50.23,tag:"oil",note:"Fell as much as ~4% on the reserve release news, then pared losses"},
    {id:"hh",nm:"US nat gas (HH)",px:3.01,dp:2,pre:"$",u:"per MMBtu",d:1.45,m:0.53,y:-11.90,tag:"gas",note:"Storage +64 bcf, below the 80 bcf five-year average build"},
    {id:"ttf",nm:"EU gas (TTF)",px:76.10,dp:2,pre:"€",u:"per MWh",d:2.92,m:5.98,y:142.07,tag:"gas",note:"Traders add positions before the weekend; storage 71% vs 87%"},
    {id:"gold",nm:"Gold",px:4139,dp:0,pre:"$",u:"per troy oz · spot",d:-0.94,m:-7.49,y:6.49,tag:"metals",note:"Day's range $4,125–4,226; second weekly loss"},
    {id:"silver",nm:"Silver",px:60.06,dp:2,pre:"$",u:"per troy oz",d:-0.73,m:-10.31,y:25.15,tag:"metals",note:"Dipped below $60 intraday; holding the line for now"},
    {id:"btc",nm:"Bitcoin",px:84555,dp:0,pre:"$",u:"approx. spot",d:-0.35,m:4.05,y:-30.85,tag:"crypto",note:"Little changed after the jobs data"},
    {id:"eth",nm:"Ether",px:2700,dp:0,pre:"$",u:"approx. spot",d:-0.22,m:7.64,y:-40.21,tag:"crypto",note:"Holding near $2,700"}
  ],
  extraTape: [["US payrolls","+29k","vs ~90k expected; −60k revisions"],["Unemployment","4.2%","up from 4.1%"],["US 10Y","~5.27%","dipped ~8bp on data, then rebounded"],["US 30Y","~5.63%","near 2002 highs"],["DXY","101.91","−0.18%"],["Fed funds","3.75–4.00%","Oct hike odds ~12–25%; Dec ~80%"],["EUR/USD","1.1266","+0.20%"],["USD/JPY","157.79","−0.19%"],["EZ inflation","3.8%","highest since Sep 2023"]],
  chain: [
    ["Jobs miss","Only 29,000 jobs; 60,000 cut from prior months.","UE 4.2% · pay +0.1%"],
    ["Hike bets drop","October hike odds fall; December still likely.","Oct ~12–25% · Dec ~80%"],
    ["Bonds bounce, then slip","10-year fell ~8bp, then gave it back.","~5.27%"],
    ["Gold spikes, then fades","Ran to $4,226 on the data, then sold off.","$4,137 · −1%"],
    ["G7 opens the taps","Up to 100m barrels of crude and diesel over four months.","Diesel front-loaded"],
    ["Oil eases","WTI down ~1.5%, Brent under 1%; supply risks remain.","Brent ~$101.4"]
  ],
  stories: [
    {tag:"rates",tags:["Fed","Jobs","Yields"],impact:5,
     h:"US adds just 29,000 jobs; October Fed hike now looks unlikely",
     happened:"<p>Nonfarm payrolls rose by 29,000 in September, well below the roughly 90,000 expected. July was revised down by 31,000 and August by 29,000. The unemployment rate rose to 4.2% from 4.1%. Average hourly earnings rose only 0.1% on the month and 3.0% on the year. Health care added 17,000 jobs; financial activities lost 7,000.</p><p>Treasuries rallied on the release: the 10-year yield fell as much as 8 basis points. It then reversed and is near 5.27%, slightly higher on the day. US stock futures rose about 0.5–0.9% after the data.</p>",
     why:"<p>Slow hiring and soft pay growth mean the Fed has less reason to hike again this month. Traders cut October hike odds to somewhere between about 12% and 25%. But about 80% still expect a hike by December, because inflation is running near 3% and Thursday's ISM survey showed factory prices paid jumping to 77.9. That is why long yields did not fall for long.</p>",
     days:"<ul><li>Monday 19:00 PKT: ISM services, with its prices index.</li><li>Fed speakers next week will show whether officials read this as a reason to wait (analysis).</li></ul>",
     months:"<ul><li>Base case: the Fed skips October and hikes in December, unless jobs data weakens further (analysis).</li><li>28 October FOMC decision.</li></ul>",
     src:[0,8,9,10,28,30]},
    {tag:"oil",tags:["Oil","G7","Diesel"],impact:5,
     h:"G7 agrees to release up to 100 million barrels of crude and diesel",
     happened:"<p>G7 leaders, in a meeting chaired by French President Emmanuel Macron, agreed to release up to 100 million barrels of oil and diesel from emergency reserves over four months, coordinated by the International Energy Agency. A large diesel release is front-loaded into the first 20 days, and the group will meet again to discuss more diesel if needed. President Trump said Europe had agreed to release 'a massive amount' of diesel.</p><p>WTI fell as much as about 4% and is near $91.50, down about 1.5%. Separately, Bloomberg reports Saudi Arabia has lifted flows on its key pipeline to over 80% of capacity, moving more crude around Hormuz. Brent is near $101.40, down about 0.9%. US diesel averages $6.37 a gallon, close to its 22 September record of $6.52.</p>",
     why:"<p>Diesel is the tightest part of the market. China has halted most October fuel exports and Russia has extended its diesel export ban, so emergency barrels target the real shortage. But 100 million barrels over four months is less than one million barrels a day, small next to the supply lost through Hormuz (analysis).</p>",
     days:"<ul><li>Sunday: OPEC+ meets, expected to keep November targets unchanged.</li><li>Brent: support $97–100, resistance $104 (analysis).</li></ul>",
     months:"<ul><li>The release can cap price spikes through winter, but it does not fix the Gulf supply problem (analysis).</li></ul>",
     src:[1,2,11,12,13,27]},
    {tag:"oil",tags:["Iran","Hormuz","Geopolitics"],impact:4,
     h:"Iran studies the US counterproposal as Trump calls its plan 'unacceptable'",
     happened:"<p>Iran says it received a formal US counterproposal through Qatari mediators on 1 October and is considering it. Foreign Minister Abbas Araghchi said Tehran's position has not changed. Trump called Iran's seven-day plan to reopen the Strait of Hormuz 'unacceptable'. US officials told the Wall Street Journal that new airstrikes are likely after the November elections. The US is deploying Patriot air defences to protect Saudi and Qatari energy sites.</p>",
     why:"<p>Both sides are still talking, but neither has moved. With tankers attacked in the strait this week, the risk of a supply shock stays in oil and gas prices, even after the G7 release (analysis).</p>",
     days:"<ul><li>Iran's reply is the main weekend risk; markets reopen in Asia on Monday.</li></ul>",
     months:"<ul><li>3 November midterms: the period after the vote is when US officials say strikes could resume.</li></ul>",
     src:[14,15,13]},
    {tag:"metals",tags:["Gold","Silver"],impact:4,
     h:"Gold spikes to $4,226 on the jobs miss, then gives it all back",
     happened:"<p>Spot gold jumped to about $4,226 right after the jobs report, then fell to near $4,137, down about 1% on the day. It is heading for a second straight weekly loss, down more than 3% this week and about 7.5% this month. Silver is near $60.06, down about 0.7%, and about 10% lower on the month.</p>",
     why:"<p>The weak jobs data helped gold at first by cutting hike odds. But long-term yields bounced back toward 2002 highs, and that pulled gold down again. A December hike is still expected, so traders are not yet ready to buy gold on Fed hopes alone.</p>",
     days:"<ul><li>Support $4,125 (today's low) then $4,100; resistance $4,226 then $4,300 (analysis).</li><li>Silver needs to get back above $60 to steady.</li></ul>",
     months:"<ul><li>Gold probably needs yields to peak, likely once the Fed signals it is done, before it can recover (analysis).</li></ul>",
     src:[3,4,16,17,29]},
    {tag:"rates",tags:["Europe","ECB","Euro"],impact:3,
     h:"Eurozone inflation jumps to 3.8%, the highest since September 2023",
     happened:"<p>Eurozone inflation rose to 3.8% in September from 3.2%, mainly because of fuel costs. That is far above the ECB's 2% target. EUR/USD is near 1.1266, up about 0.2% after the US jobs miss, but down about 3% this month. The dollar index is near 101.91, down about 0.2%. USD/JPY is near 157.8.</p>",
     why:"<p>Higher inflation puts pressure on the ECB to keep raising rates, which could support the euro. But French fiscal worries and slow growth limit how fast it can move. For now the dollar stays strong because US yields are much higher (analysis).</p>",
     days:"<ul><li>ECB speakers next week; watch for talk of a faster pace of hikes.</li></ul>",
     months:"<ul><li>If energy prices stay high, eurozone inflation could stay near 4% into winter (analysis).</li></ul>",
     src:[5,6,7]},
    {tag:"gas",tags:["Nat gas","Europe","LNG"],impact:3,
     h:"European gas jumps 3% before the weekend; US storage build below normal",
     happened:"<p>EU gas (TTF) is near €76.10/MWh, up about 2.9%, as traders add positions before the weekend. It is up about 6% on the month and more than double a year ago. US Henry Hub is near $3.01/MMBtu, up about 1.5%. The EIA reported a 64 bcf storage build, in line with forecasts but below the 80 bcf five-year average.</p>",
     why:"<p>EU storage is about 71% full against a normal 87%, and Hormuz attacks this week hit LNG tankers too. In the US, record output of about 113 bcf a day and normal weather through mid-October keep prices low, even with LNG export demand near 17.9 bcf a day.</p>",
     days:"<ul><li>Thursday 19:30 PKT: next EIA storage report.</li><li>Weekend Hormuz news would move TTF first on Monday.</li></ul>",
     months:"<ul><li>A cold start to winter with storage this low could send TTF sharply higher (analysis).</li></ul>",
     src:[18,19,26]},
    {tag:"crypto",tags:["Bitcoin","Ether"],impact:2,
     h:"Bitcoin steady near $84,500 after the jobs data",
     happened:"<p>Bitcoin is near $84,555, down about 0.35% on the day, and ether near $2,700, down about 0.2%. Both are higher on the month but far below their levels a year ago.</p>",
     why:"<p>Lower odds of an October hike help a little, but yields that bounced back limit the gains.</p>",
     days:"<ul><li>Support $83,000; resistance near $85,800 (analysis).</li></ul>",
     months:"<ul><li>A lasting rally probably needs yields to stop rising (analysis).</li></ul>",
     src:[20]}
  ],
  calendar: [
    {k:"Fri",d:"2 Oct",ev:[
      {t:"14:00",n:"Eurozone CPI flash (Sep)",c:"3.8% vs prior 3.2% (out)",i:"m",x:"Highest since Sep 2023; pressure on the ECB."},
      {t:"17:30",n:"US nonfarm payrolls (Sep)",c:"+29k vs ~90k exp.; UE 4.2% (out)",i:"h",x:"October hike odds fall; December still priced."},
      {t:"22:00",n:"Baker Hughes rig count",c:"Weekly",i:"m",x:"More rigs would signal US output rising to meet high prices."},
      {t:"00:30",n:"CFTC positioning (Sat, PKT)",c:"Weekly",i:"m",x:"Shows whether funds cut gold longs this week."}]},
    {k:"Mon",d:"5 Oct",ev:[
      {t:"Open",n:"OPEC+ decision (Sunday) priced in",c:"Nov targets expected unchanged",i:"m",x:"A surprise, or weekend Iran news, would gap prices at the Asia open."},
      {t:"19:00",n:"US ISM services (Sep)",c:"Activity & prices",i:"h",x:"Hot prices would revive October hike bets after the jobs miss."}]},
    {k:"Tue",d:"6 Oct",ev:[
      {t:"21:00",n:"SPR exchange bids due",c:"Up to 40m barrels",i:"m",x:"Adds to the G7 release; strong bidding weighs on WTI."}]},
    {k:"Wed",d:"7 Oct",ev:[
      {t:"All day",n:"China Golden Week ends",c:"Fuel export halt runs at least to here",i:"m",x:"An extension would keep Asian fuel prices high."},
      {t:"19:30",n:"EIA weekly oil report",c:"Crude, gasoline, distillates",i:"m",x:"Diesel stocks show whether the G7 release is reaching the market."},
      {t:"23:00",n:"FOMC minutes (Sep meeting, expected)",c:"After the Sept hike",i:"m",x:"Shows how many officials want more hikes after the jobs miss."}]},
    {k:"Thu",d:"8 Oct",ev:[
      {t:"17:30",n:"US jobless claims",c:"Weekly",i:"m",x:"After the payrolls miss, a rise would add to the case for a pause."},
      {t:"19:30",n:"EIA natural gas storage",c:"Weekly injection",i:"m",x:"Another below-normal build would support Henry Hub."}]}
  ],
  later: [["4 Oct","OPEC+ online meeting · Nov targets"],["28 Oct","FOMC decision · Oct hike odds ~12–25%"],["29–30 Oct","Bank of Japan meeting · hike in play after Tokyo CPI"],["3 Nov","US midterm elections · strikes on Iran seen likely after"],["Jan","G7 reserve release runs about four months"]],
  scenarios: [
    {id:"deal",nm:"Iran says yes",sub:"Tehran accepts the US counterproposal and Hormuz opens step by step",
     m:{Oil:"dn2",Gas:"dn",Gold:"up",Silver:"up",Dollar:"dn",Yields:"dn",BTC:"up",ETH:"up"},
     why:"With the G7 release already coming, a deal would knock a lot off oil. Lower oil plus weak jobs would pull yields and the dollar down: the best setup for gold, silver and crypto."},
    {id:"stall",nm:"Stalemate",sub:"Base case: talks drag on, Fed skips October, hike in December",
     m:{Oil:"fl",Gas:"up",Gold:"fl",Silver:"fl",Dollar:"fl",Yields:"mix",BTC:"fl",ETH:"fl"},
     why:"The reserve release caps Brent near $100–104 while Hormuz risk keeps a floor. Long yields stay high on inflation worries even as hike odds fall. Gold and silver chop; EU gas grinds higher into winter."},
    {id:"esc",nm:"Escalation",sub:"More tanker strikes, or Iran rejects the proposal",
     m:{Oil:"up2",Gas:"up2",Gold:"mix",Silver:"dn",Dollar:"up",Yields:"up",BTC:"dn",ETH:"dn"},
     why:"Oil and gas spike despite the G7 barrels. Higher oil feeds the bond selloff. Gold is torn between safe-haven buying and higher yields; silver and crypto likely fall."}
  ],
  levels: [
    ["Brent (Dec)","$97 · $100 · $104","Support; round number; resistance."],
    ["WTI","$89.4 · $92","Today's low; resistance."],
    ["Gold","$4,125 · $4,226","Today's low; today's post-jobs high."],
    ["Silver","$60","Tested today; a close below opens the way lower."],
    ["US 10Y","5.34%","This week's high, highest since 2002."],
    ["DXY","101.8–102","Year's high area."],
    ["EUR/USD","1.13","Broken this week; lowest since May 2025."],
    ["USD/JPY","158–160","Zone where Tokyo has acted before."],
    ["Bitcoin","$83k · $85.8k","Support; resistance."],
    ["EU storage","71% vs 87%","Current fill vs five-year average."]
  ],
  wire: [
    {d:"2 Oct",tag:"Oil",h:"G7 to Release Up to 100 Million Barrels of Diesel, Crude",url:"https://www.bloomberg.com/news/articles/2026-10-02/g7-to-release-up-to-100-millions-of-barrels-of-diesel-and-oil",why:"The main reason oil fell today."},
    {d:"2 Oct",tag:"Rates",h:"US Jobs Report September 2026: Live News on Employment, Payrolls",url:"https://www.bloomberg.com/news/live-blog/2026-10-02/us-employment-report-for-september",why:"Running coverage of the jobs miss that cut October hike bets."},
    {d:"2 Oct",tag:"Rates",h:"Bond Traders Cut Fed Rate Hike Bets After Weak US Jobs Report",url:"https://www.bloomberg.com/news/articles/2026-10-02/bond-traders-pull-back-on-fed-hike-bets-after-soft-jobs-data",why:"October hike odds fell, but long yields stayed near 2002 highs."},
    {d:"2 Oct",tag:"Oil",h:"Saudi Arabia Hikes Oil Flow on Key Pipeline to Over 80% Capacity",url:"https://www.bloomberg.com/news/articles/2026-10-02/saudi-arabia-hikes-oil-flow-on-key-pipeline-to-over-80-capacity",why:"More Saudi crude bypassing Hormuz eases part of the supply gap."},
    {d:"1 Oct",tag:"Gold",h:"Gold Holds Steady as Traders Weigh Higher Bond Yields, Oil",url:"https://www.bloomberg.com/news/articles/2026-10-01/gold-steady-as-softer-inflation-data-tempers-fed-rate-hike-bets",why:"Yields are the main weight on gold this week."},
    {d:"1 Oct",tag:"Rates",h:"Why Are Bond Yields Higher Globally? Investors React to Inflation, Fiscal Risks",url:"https://www.bloomberg.com/news/articles/2026-10-01/ten-reasons-investors-are-driving-government-bond-yields-higher",why:"Why yields bounced back even after weak jobs."}
  ],
  sources: [
    ["BLS · Employment Situation, September 2026","https://www.bls.gov/news.release/empsit.nr0.htm"],
    ["Trading Economics · Brent crude","https://tradingeconomics.com/commodity/brent-crude-oil"],
    ["Trading Economics · WTI crude","https://tradingeconomics.com/commodity/crude-oil"],
    ["Trading Economics · Gold","https://tradingeconomics.com/commodity/gold"],
    ["Trading Economics · Silver","https://tradingeconomics.com/commodity/silver"],
    ["Trading Economics · EUR/USD","https://tradingeconomics.com/euro-area/currency"],
    ["Trading Economics · US dollar index","https://tradingeconomics.com/united-states/currency"],
    ["Trading Economics · USD/JPY","https://tradingeconomics.com/japan/currency"],
    ["Trading Economics · US 10Y yield","https://tradingeconomics.com/united-states/government-bond-yield"],
    ["Investing.com (Reuters) · Soft September jobs report sends markets higher","https://investing.com/news/economy-news/soft-september-jobs-report-sends-markets-higher-4929845"],
    ["Verified Investing · ISM manufacturing September 2026","https://verifiedinvesting.com/blogs/us-economic-metrics/ism-manufacturing-september-2026"],
    ["Al Jazeera · G7 announces oil reserve release","https://www.aljazeera.com/news/2026/10/2/trump-says-europe-agrees-to-release-massive-amount-diesel-stockpile"],
    ["Helsinki Times · G7 to release 100 million barrels","https://www.helsinkitimes.fi/world-int/29338-g7-to-release-100-million-barrels-of-oil-and-diesel-from-emergency-reserves.html"],
    ["OilPrice.com · Prices and headlines","https://oilprice.com/"],
    ["EA WorldView · US war on Iran, day 217","https://eaworldview.com/2026/10/us-war-on-iran-trump-rejects-tehran-proposal-to-reopen-talks-and-strait-of-hormuz/"],
    ["Middle East Monitor · Tehran receives US response to Hormuz proposal","https://www.middleeastmonitor.com/20261001-tehran-receives-us-response-to-hormuz-reopening-proposal-but-differences-remain-over-implementation/"],
    ["Kitco · Gold price","https://www.kitco.com/charts/gold"],
    ["Business Recorder (Reuters) · Gold slips before US payrolls data","https://www.brecorder.com/news/40442314/gold-slips-before-us-payrolls-data-set-for-second-weekly-loss"],
    ["Trading Economics · EU natural gas","https://tradingeconomics.com/commodity/eu-natural-gas"],
    ["Trading Economics · US natural gas","https://tradingeconomics.com/commodity/natural-gas"],
    ["Trading Economics · Crypto","https://tradingeconomics.com/crypto"],
    ["Yahoo Finance · Stock market today, 2 Oct","https://finance.yahoo.com/markets/live/stock-market-today-friday-october-2-dow-sp-500-nasdaq-september-jobs-report-080623878.html"],
    ["Bloomberg · G7 to release up to 100 million barrels of diesel, crude","https://www.bloomberg.com/news/articles/2026-10-02/g7-to-release-up-to-100-millions-of-barrels-of-diesel-and-oil"],
    ["Bloomberg · US jobs report September 2026 live blog","https://www.bloomberg.com/news/live-blog/2026-10-02/us-employment-report-for-september"],
    ["Bloomberg · Treasuries rebound raises stakes for job data","https://www.bloomberg.com/news/articles/2026-10-02/treasuries-rebound-raises-stakes-for-job-data-as-rate-hikes-loom"],
    ["Bloomberg · China cancels some fuel shipments to support domestic supply","https://www.bloomberg.com/news/articles/2026-10-01/china-cancels-some-fuel-shipments-to-support-domestic-supply"],
    ["Bloomberg · Europe draws more LNG as Hormuz crisis tightens global market","https://bloomberg.com/news/articles/2026-09-28/europe-draws-more-lng-as-hormuz-crisis-tightens-global-market"],
    ["Bloomberg · Saudi Arabia hikes oil flow on key pipeline","https://www.bloomberg.com/news/articles/2026-10-02/saudi-arabia-hikes-oil-flow-on-key-pipeline-to-over-80-capacity"],
    ["Bloomberg · Bond traders cut Fed hike bets after weak jobs report","https://www.bloomberg.com/news/articles/2026-10-02/bond-traders-pull-back-on-fed-hike-bets-after-soft-jobs-data"],
    ["Bloomberg · Gold holds steady as traders weigh higher bond yields, oil","https://www.bloomberg.com/news/articles/2026-10-01/gold-steady-as-softer-inflation-data-tempers-fed-rate-hike-bets"],
    ["TheStreet · Stock market today, 2 Oct 2026","https://thestreet.com/stock-market-today/stock-market-today-dow-jones-sp-500-nasdaq-updates-oct-02-2026"]
  ]
};
/* ===== END EDITION DATA ===== */
